require("devbox.plugins-setup")
require("devbox.core.colorscheme")
require("devbox.core.options")
require("devbox.core.keymaps")
require("devbox.plugins.nvim-tree")
require("devbox.plugins.lualine")
require("devbox.plugins.telescope")
require("devbox.plugins.nvim-cmp")
require("devbox.plugins.comment")
require("devbox.plugins.lsp.mason")
require("devbox.plugins.lsp.lspsaga")
require("devbox.plugins.lsp.lspconfig")

